# -*- coding: utf-8 -*-
"""multiagente_Mundial (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJS9hqjL8fjhCxM9K9N5KQd3oASw8xFz

# Pipeline Multiagente - Analisis de Partidos de la Copa del Mundo

Pipeline con 3 agentes especializados:
1. **Normalizador** - limpieza, imputacion, feature engineering y codificacion
2. **Entrenador** - Random Forest Classifier (prediccion de resultado)
3. **Comunicador** - reporte de metricas en lenguaje natural

## 0. Instalación de dependencias
"""

import subprocess, sys

for pkg in ["pandas", "numpy", "scikit-learn", "requests", "matplotlib", "seaborn"]:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

print("Dependencias listas.")

"""## 1. Imports y configuración"""

import pandas as pd
import numpy as np
import warnings
import requests
import json
import re
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

warnings.filterwarnings('ignore')
print("Imports correctos.")

"""## 2. Carga del Dataset"""

from google.colab import files

print("Seleccioná el archivo wc_all_matches.csv:")
uploaded = files.upload()

CSV_FILE = list(uploaded.keys())[0]
print(f"Archivo '{CSV_FILE}' cargado.")

df_wc = pd.read_csv(CSV_FILE)
print(f"Dataset cargado → {df_wc.shape[0]} partidos | {df_wc['year'].min()}–{df_wc['year'].max()}")
print(f"   Columnas: {list(df_wc.columns)}")
df_wc.head(8)

"""## Agente 1 — Normalizador

Limpia, crea features derivadas, codifica categóricas y escala variables numéricas.
"""

class NormalizerAgent:
    """Limpieza, feature engineering, codificación y escalado del dataset Mundial."""

    def __init__(self):
        self.le_stage   = LabelEncoder()
        self.le_team1   = LabelEncoder()
        self.le_team2   = LabelEncoder()
        self.le_country = LabelEncoder()
        self.scaler     = MinMaxScaler()

    def process(self, df: pd.DataFrame):
        print("[Agente 1 - Normalizador]: Iniciando normalización...")
        df_clean = df.copy()

        # 1. Limpieza
        nulos_antes = df_clean.isnull().sum().sum()
        df_clean['notes'] = df_clean['notes'].fillna('Sin nota')
        df_clean['date']  = pd.to_datetime(df_clean['date'], errors='coerce')
        df_clean = df_clean.dropna(subset=['score1', 'score2'])
        print(f"   Nulos: {nulos_antes} → {df_clean.isnull().sum().sum()}")

        # 2. Feature engineering
        df_clean['total_goles']          = df_clean['score1'] + df_clean['score2']
        df_clean['diferencia_goles']     = df_clean['score1'] - df_clean['score2']
        df_clean['es_empate']            = (df_clean['score1'] == df_clean['score2']).astype(int)
        df_clean['partido_alto_scoring'] = (df_clean['total_goles'] > 3).astype(int)
        df_clean['decada']               = (df_clean['year'] // 10) * 10
        df_clean['resultado'] = df_clean['diferencia_goles'].apply(
            lambda x: 'victoria' if x > 0 else ('derrota' if x < 0 else 'empate')
        )
        df_clean['resultado_enc'] = df_clean['resultado'].map({'victoria':2,'empate':1,'derrota':0})
        print("   Features: total_goles, diferencia_goles, es_empate, decada, resultado")

        # 3. Codificación
        df_clean['stage_enc']   = self.le_stage.fit_transform(df_clean['stage'])
        df_clean['team1_enc']   = self.le_team1.fit_transform(df_clean['team1'])
        df_clean['team2_enc']   = self.le_team2.fit_transform(df_clean['team2'])
        df_clean['country_enc'] = self.le_country.fit_transform(df_clean['country'])
        print("   Codificación: stage, team1, team2, country → _enc")

        # 4. Escalado
        cols_num = ['year','score1','score2','total_goles','diferencia_goles']
        scaled   = self.scaler.fit_transform(df_clean[cols_num])
        for i, col in enumerate(cols_num):
            df_clean[col + '_scaled'] = scaled[:, i]
        print("   Escalado MinMax aplicado")

        print(f"[Agente 1]: Dataset limpio → {df_clean.shape[0]} filas × {df_clean.shape[1]} cols")
        return df_clean


TARGET_COL = 'resultado_enc'

agente_normalizador = NormalizerAgent()
df_limpio = agente_normalizador.process(df_wc)
df_limpio[['year','stage','team1','score1','score2','team2','total_goles','resultado','decada']].head(8)

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

df_limpio['total_goles'].hist(ax=axes[0], bins=15, color='steelblue', edgecolor='white')
axes[0].set_title('Distribución de Goles por Partido')

df_limpio['resultado'].value_counts().plot(kind='bar', ax=axes[1],
    color=['#2ecc71','#e74c3c','#95a5a6'], edgecolor='white')
axes[1].set_title('Resultados (perspectiva team1)')
axes[1].tick_params(axis='x', rotation=0)

df_limpio.groupby('decada')['total_goles'].mean().plot(kind='bar', ax=axes[2],
    color='coral', edgecolor='white')
axes[2].set_title('Promedio Goles por Década')

plt.suptitle('Dataset Copa del Mundo 1930–2022', fontsize=13, y=1.02)
plt.tight_layout()
plt.show()

"""## Agente 2 — Entrenador"""

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

df_limpio['total_goles'].hist(ax=axes[0], bins=15, color='steelblue', edgecolor='white')
axes[0].set_title('Distribución de Goles por Partido')

df_limpio['resultado'].value_counts().plot(kind='bar', ax=axes[1],
    color=['#2ecc71','#e74c3c','#95a5a6'], edgecolor='white')
axes[1].set_title('Resultados (perspectiva team1)')
axes[1].tick_params(axis='x', rotation=0)

df_limpio.groupby('decada')['total_goles'].mean().plot(kind='bar', ax=axes[2],
    color='coral', edgecolor='white')
axes[2].set_title('Promedio Goles por Década')

plt.suptitle('Dataset Copa del Mundo 1930–2022', fontsize=13, y=1.02)
plt.tight_layout()
plt.show()

"""## Agente 3 — Comunicador

Tiene dos funciones sobre el mismo dataset:
1. **Reporte ejecutivo** — calcula metricas e insights y los redacta en lenguaje natural.
2. **Chatbot interactivo** — responde preguntas sobre partidos reales buscando en el dataset y usando Mistral como motor de lenguaje.

La API key de Mistral se carga en `MISTRAL_API_KEY`. Sin key, ambas funciones trabajan en modo offline (solo datos del dataset).
"""

class TrainerAgent:
    """Entrena Random Forest Classifier con validación cruzada estratificada."""

    FEATURES = [
        'year_scaled','stage_enc','team1_enc','team2_enc',
        'country_enc','decada','es_empate','partido_alto_scoring'
    ]

    def __init__(self):
        self.model    = RandomForestClassifier(n_estimators=200, max_depth=15,
                                               random_state=42, n_jobs=-1)
        self.metricas = {}

    def process(self, df: pd.DataFrame, target_column: str):
        print("[Agente 2 - Entrenador]: Iniciando entrenamiento...")
        X = df[self.FEATURES]
        y = df[target_column]

        cv     = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        scores = cross_val_score(self.model, X, y, cv=cv, scoring='accuracy')
        print(f"   CV (5-fold): {scores.mean():.4f} ± {scores.std():.4f}")

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, stratify=y, random_state=42)
        self.model.fit(X_train, y_train)
        y_pred = self.model.predict(X_test)

        self.metricas = {
            'accuracy_cv_media': round(float(scores.mean()), 4),
            'accuracy_cv_std'  : round(float(scores.std()),  4),
            'accuracy_test'    : round(float(accuracy_score(y_test, y_pred)), 4),
            'y_test'           : y_test.tolist(),
            'y_pred'           : y_pred.tolist(),
            'confusion_matrix' : confusion_matrix(y_test, y_pred).tolist(),
        }
        print(f"[Agente 2]: Accuracy test = {self.metricas['accuracy_test']:.4f}")
        return self.model, self.metricas


agente_entrenador = TrainerAgent()
modelo_entrenado, metricas_modelo = agente_entrenador.process(df_limpio, TARGET_COL)

print("\nReporte de clasificación:")
print(classification_report(metricas_modelo['y_test'], metricas_modelo['y_pred'],
      target_names=['Derrota','Empate','Victoria']))

# Matriz de confusión
cm = np.array(metricas_modelo['confusion_matrix'])
fig, ax = plt.subplots(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Derrota','Empate','Victoria'],
            yticklabels=['Derrota','Empate','Victoria'], ax=ax)
ax.set_xlabel('Predicho'); ax.set_ylabel('Real')
ax.set_title('Matriz de Confusión — Random Forest')
plt.tight_layout(); plt.show()

"""### Chat interactivo con el Comunicador

Ejecuta la celda de abajo y escribí tus preguntas. Para terminar, escribí `salir`.

Ejemplos:
- ¿Como le fue a Argentina en el mundial 2022?
- ¿Cual fue el resultado de la final del mundial 1986?
- ¿Que partidos jugo Brasil en 1970?
- ¿Quien gano el mundial de 1998?
"""

# Chat interactivo del Agente 3 (Comunicador).
# Necesita MISTRAL_API_KEY cargada arriba para respuestas completas;
# sin key responde en modo offline con los datos del dataset.
agente_comunicador.iniciar_sesion()

"""## Resumen del Pipeline"""

