# -*- coding: utf-8 -*-
"""multiagente_Mundial (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJS9hqjL8fjhCxM9K9N5KQd3oASw8xFz

# Pipeline Multiagente - Analisis de Partidos de la Copa del Mundo

Pipeline con 3 agentes especializados:
1. **Normalizador** - limpieza, imputacion, feature engineering y codificacion
2. **Entrenador** - Random Forest Classifier (prediccion de resultado)
3. **Comunicador** - reporte de metricas en lenguaje natural

## 0. Instalación de dependencias
"""

import subprocess, sys

for pkg in ["pandas", "numpy", "scikit-learn", "requests", "matplotlib", "seaborn"]:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

print("Dependencias listas.")

"""## 1. Imports y configuración"""

import pandas as pd
import numpy as np
import warnings
import requests
import json
import re
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

warnings.filterwarnings('ignore')
print("Imports correctos.")

"""## 2. Carga del Dataset"""

from google.colab import files

print("Seleccioná el archivo wc_all_matches.csv:")
uploaded = files.upload()

CSV_FILE = list(uploaded.keys())[0]
print(f"Archivo '{CSV_FILE}' cargado.")

df_wc = pd.read_csv(CSV_FILE)
print(f"Dataset cargado → {df_wc.shape[0]} partidos | {df_wc['year'].min()}–{df_wc['year'].max()}")
print(f"   Columnas: {list(df_wc.columns)}")
df_wc.head(8)

"""## Agente 1 — Normalizador

Limpia, crea features derivadas, codifica categóricas y escala variables numéricas.
"""

class NormalizerAgent:
    """Limpieza, feature engineering, codificación y escalado del dataset Mundial."""

    def __init__(self):
        self.le_stage   = LabelEncoder()
        self.le_team1   = LabelEncoder()
        self.le_team2   = LabelEncoder()
        self.le_country = LabelEncoder()
        self.scaler     = MinMaxScaler()

    def process(self, df: pd.DataFrame):
        print("[Agente 1 - Normalizador]: Iniciando normalización...")
        df_clean = df.copy()

        # 1. Limpieza
        nulos_antes = df_clean.isnull().sum().sum()
        df_clean['notes'] = df_clean['notes'].fillna('Sin nota')
        df_clean['date']  = pd.to_datetime(df_clean['date'], errors='coerce')
        df_clean = df_clean.dropna(subset=['score1', 'score2'])
        print(f"   Nulos: {nulos_antes} → {df_clean.isnull().sum().sum()}")

        # 2. Feature engineering
        df_clean['total_goles']          = df_clean['score1'] + df_clean['score2']
        df_clean['diferencia_goles']     = df_clean['score1'] - df_clean['score2']
        df_clean['es_empate']            = (df_clean['score1'] == df_clean['score2']).astype(int)
        df_clean['partido_alto_scoring'] = (df_clean['total_goles'] > 3).astype(int)
        df_clean['decada']               = (df_clean['year'] // 10) * 10
        df_clean['resultado'] = df_clean['diferencia_goles'].apply(
            lambda x: 'victoria' if x > 0 else ('derrota' if x < 0 else 'empate')
        )
        df_clean['resultado_enc'] = df_clean['resultado'].map({'victoria':2,'empate':1,'derrota':0})
        print("   Features: total_goles, diferencia_goles, es_empate, decada, resultado")

        # 3. Codificación
        df_clean['stage_enc']   = self.le_stage.fit_transform(df_clean['stage'])
        df_clean['team1_enc']   = self.le_team1.fit_transform(df_clean['team1'])
        df_clean['team2_enc']   = self.le_team2.fit_transform(df_clean['team2'])
        df_clean['country_enc'] = self.le_country.fit_transform(df_clean['country'])
        print("   Codificación: stage, team1, team2, country → _enc")

        # 4. Escalado
        cols_num = ['year','score1','score2','total_goles','diferencia_goles']
        scaled   = self.scaler.fit_transform(df_clean[cols_num])
        for i, col in enumerate(cols_num):
            df_clean[col + '_scaled'] = scaled[:, i]
        print("   Escalado MinMax aplicado")

        print(f"[Agente 1]: Dataset limpio → {df_clean.shape[0]} filas × {df_clean.shape[1]} cols")
        return df_clean


TARGET_COL = 'resultado_enc'

agente_normalizador = NormalizerAgent()
df_limpio = agente_normalizador.process(df_wc)
df_limpio[['year','stage','team1','score1','score2','team2','total_goles','resultado','decada']].head(8)

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

df_limpio['total_goles'].hist(ax=axes[0], bins=15, color='steelblue', edgecolor='white')
axes[0].set_title('Distribución de Goles por Partido')

df_limpio['resultado'].value_counts().plot(kind='bar', ax=axes[1],
    color=['#2ecc71','#e74c3c','#95a5a6'], edgecolor='white')
axes[1].set_title('Resultados (perspectiva team1)')
axes[1].tick_params(axis='x', rotation=0)

df_limpio.groupby('decada')['total_goles'].mean().plot(kind='bar', ax=axes[2],
    color='coral', edgecolor='white')
axes[2].set_title('Promedio Goles por Década')

plt.suptitle('Dataset Copa del Mundo 1930–2022', fontsize=13, y=1.02)
plt.tight_layout()
plt.show()

"""## Agente 2 — Entrenador"""

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

df_limpio['total_goles'].hist(ax=axes[0], bins=15, color='steelblue', edgecolor='white')
axes[0].set_title('Distribución de Goles por Partido')

df_limpio['resultado'].value_counts().plot(kind='bar', ax=axes[1],
    color=['#2ecc71','#e74c3c','#95a5a6'], edgecolor='white')
axes[1].set_title('Resultados (perspectiva team1)')
axes[1].tick_params(axis='x', rotation=0)

df_limpio.groupby('decada')['total_goles'].mean().plot(kind='bar', ax=axes[2],
    color='coral', edgecolor='white')
axes[2].set_title('Promedio Goles por Década')

plt.suptitle('Dataset Copa del Mundo 1930–2022', fontsize=13, y=1.02)
plt.tight_layout()
plt.show()

"""## Agente 3 — Comunicador

Tiene dos funciones sobre el mismo dataset:
1. **Reporte ejecutivo** — calcula metricas e insights y los redacta en lenguaje natural.
2. **Chatbot interactivo** — responde preguntas sobre partidos reales buscando en el dataset y usando Mistral como motor de lenguaje.

La API key de Mistral se carga en `MISTRAL_API_KEY`. Sin key, ambas funciones trabajan en modo offline (solo datos del dataset).
"""

class CommunicatorAgent:
    """Agente 3 - Comunicador.

    Cumple dos funciones sobre el mismo dataset:
      1. process()        -> genera el reporte ejecutivo (con Mistral si hay
                             API key, o en modo offline determinista).
      2. iniciar_sesion() -> chatbot interactivo que responde preguntas sobre
                             partidos reales: busca en el dataset y usa Mistral
                             como motor de lenguaje natural.
    """

    MISTRAL_URL = "https://api.mistral.ai/v1/chat/completions"
    MODEL       = "mistral-small-latest"

    STAGES = [
        "group stage", "round of 16", "quarter-final", "semi-final",
        "final round", "final", "3rd place",
    ]

    def __init__(self, df: pd.DataFrame, api_key: str = "TU_API_KEY_MISTRAL"):
        self.api_key = api_key
        self.df = df.copy()
        self.df['team1_lower'] = self.df['team1'].str.lower()
        self.df['team2_lower'] = self.df['team2'].str.lower()
        self.df['stage_lower'] = self.df['stage'].str.lower()
        self.historial = []

    @property
    def _tiene_key(self) -> bool:
        return bool(self.api_key) and self.api_key != "TU_API_KEY_MISTRAL"

    def _mistral(self, messages: list, temperature: float = 0.4) -> str:
        """Llamada generica al endpoint de Mistral."""
        headers = {
            "Content-Type" : "application/json",
            "Authorization": f"Bearer {self.api_key}",
        }
        payload = {"model": self.MODEL, "messages": messages, "temperature": temperature}
        resp = requests.post(self.MISTRAL_URL, headers=headers, json=payload, timeout=30)
        if resp.status_code == 200:
            return resp.json()["choices"][0]["message"]["content"]
        raise RuntimeError(f"API Mistral ({resp.status_code}): {resp.text}")

    # ===== 1. REPORTE EJECUTIVO =====
    def _calcular_insights(self, df_original: pd.DataFrame) -> dict:
        return {
            "anios"      : f"{int(df_original['year'].min())} - {int(df_original['year'].max())}",
            "partidos"   : len(df_original),
            "total_goles": int(df_original['score1'].sum() + df_original['score2'].sum()),
            "prom_goles" : round((df_original['score1'] + df_original['score2']).mean(), 2),
            "top_team"   : df_original.groupby('team1')['score1'].sum().sort_values(ascending=False).index[0],
            "acc_cv"     : self._met['accuracy_cv_media'] * 100,
            "acc_cv_std" : self._met['accuracy_cv_std'] * 100,
            "acc_test"   : self._met['accuracy_test'] * 100,
        }

    def _reporte_offline(self, d: dict) -> str:
        r  = "=" * 62 + "\n"
        r += "   REPORTE - COPA DEL MUNDO | Pipeline Multiagente\n"
        r += "=" * 62 + "\n\n"
        r += f"Periodo:               {d['anios']}\n"
        r += f"   Partidos analizados:  {d['partidos']}\n"
        r += f"   Total de goles:       {d['total_goles']}\n"
        r += f"   Promedio goles/ptdo:  {d['prom_goles']}\n"
        r += f"   Equipo mas goleador:  {d['top_team']}\n\n"
        r += "Modelo:                Random Forest Classifier\n"
        r += f"   Accuracy CV (5-fold): {d['acc_cv']:.2f}% +/- {d['acc_cv_std']:.2f}%\n"
        r += f"   Accuracy test:        {d['acc_test']:.2f}%\n\n"
        r += "El modelo predice victoria/empate/derrota con esos valores.\n"
        r += "El futbol es inherentemente impredecible, esto es esperable.\n"
        r += "\nPipeline completado exitosamente.\n" + "=" * 62
        return r

    def process(self, metricas: dict, df_original: pd.DataFrame = None) -> str:
        print("\n[Agente 3 - Comunicador]: Generando reporte...\n")
        self._met = metricas
        df_original = df_original if df_original is not None else self.df
        d = self._calcular_insights(df_original)

        if self._tiene_key:
            try:
                print("   Redactando reporte con Mistral...")
                system_prompt = (
                    "Sos un analista deportivo. A partir de las metricas de un pipeline "
                    "de machine learning sobre partidos de la Copa del Mundo, redacta un "
                    "reporte ejecutivo claro y profesional en espanol, de 2 a 3 parrafos. "
                    "Interpreta los numeros, no los repitas en crudo. No uses emojis."
                )
                datos = (
                    f"Periodo analizado: {d['anios']}\n"
                    f"Partidos analizados: {d['partidos']}\n"
                    f"Total de goles: {d['total_goles']}\n"
                    f"Promedio de goles por partido: {d['prom_goles']}\n"
                    f"Equipo mas goleador: {d['top_team']}\n"
                    f"Modelo: Random Forest Classifier\n"
                    f"Accuracy validacion cruzada (5-fold): {d['acc_cv']:.2f}% +/- {d['acc_cv_std']:.2f}%\n"
                    f"Accuracy en test: {d['acc_test']:.2f}%"
                )
                narrativa = self._mistral([
                    {"role": "system", "content": system_prompt},
                    {"role": "user",   "content": datos},
                ], temperature=0.4)
                reporte  = "=" * 62 + "\n"
                reporte += "   REPORTE EN LENGUAJE NATURAL - COPA DEL MUNDO\n"
                reporte += "=" * 62 + "\n\n" + narrativa.strip() + "\n\n" + "=" * 62
                print(reporte)
                return reporte
            except Exception as e:
                print(f"   No se pudo usar Mistral ({e}). Uso reporte offline.\n")

        reporte = self._reporte_offline(d)
        print(reporte)
        return reporte

    # ===== 2. CHATBOT =====
    def _extraer_anio(self, texto: str):
        matches = re.findall(r'\b(19[3-9]\d|200\d|201\d|2022)\b', texto)
        return int(matches[0]) if matches else None

    def _extraer_equipos(self, texto: str):
        texto_lower = texto.lower()
        equipos = set(self.df['team1'].unique()) | set(self.df['team2'].unique())
        return [eq for eq in equipos if re.search(rf'\b{re.escape(eq.lower())}\b', texto_lower)]

    def _extraer_fase(self, texto: str):
        texto_lower = texto.lower()
        for fase in self.STAGES:
            if fase in texto_lower:
                return fase
        aliases = {
            'final': 'final', 'semifinal': 'semi-final', 'cuartos': 'quarter-final',
            'octavos': 'round of 16', 'fase de grupos': 'group stage',
            'grupos': 'group stage', 'tercer puesto': '3rd place', 'tercer': '3rd place',
        }
        for alias, fase in aliases.items():
            if alias in texto_lower:
                return fase
        return None

    def _buscar_partidos(self, anio, equipos, fase):
        df = self.df.copy()
        filtrado = False
        if anio:
            df = df[df['year'] == anio]; filtrado = True
        if equipos:
            mask = pd.Series([False] * len(df), index=df.index)
            for eq in equipos:
                e = eq.lower()
                mask = mask | (df['team1_lower'] == e) | (df['team2_lower'] == e)
            df = df[mask]; filtrado = True
        if fase:
            df = df[df['stage_lower'].str.contains(fase, na=False)]; filtrado = True
        return df if filtrado else pd.DataFrame()

    def _formatear_partidos(self, df_result: pd.DataFrame) -> str:
        if df_result.empty:
            return ""
        tiene_notes = 'notes' in df_result.columns
        lineas = [f"Se encontraron {len(df_result)} partido(s) en el dataset:\n"]
        for _, row in df_result.iterrows():
            score = f"{int(row['score1'])}-{int(row['score2'])}"
            if row['score1'] > row['score2']:
                ganador = row['team1']
            elif row['score2'] > row['score1']:
                ganador = row['team2']
            else:
                ganador = 'Empate'
            nota = ''
            if tiene_notes:
                val = str(row['notes'])
                if val not in ('', 'Sin nota', 'nan'):
                    nota = f" ({val})"
            lineas.append(
                f"  - {int(row['year'])} | {row['stage']} | "
                f"{row['team1']} {score} {row['team2']} - {ganador}{nota}"
            )
        return "\n".join(lineas)

    def responder(self, pregunta: str) -> str:
        """Responde una sola pregunta (util para probar fuera del loop)."""
        anio    = self._extraer_anio(pregunta)
        equipos = self._extraer_equipos(pregunta)
        fase    = self._extraer_fase(pregunta)
        contexto = self._formatear_partidos(self._buscar_partidos(anio, equipos, fase))

        if not self._tiene_key:
            if contexto:
                return "Modo offline (sin API key). Datos del dataset:\n" + contexto
            return "Modo offline: no encontre partidos para esa consulta. Cargá tu API key para respuestas mas completas."

        system_prompt = (
            "Sos un asistente experto en la historia de la Copa del Mundo (1930-2022). "
            f"Tenes acceso a un dataset con {len(self.df)} partidos oficiales. "
            "Cuando recibas datos del dataset, usalos para una respuesta precisa. "
            "Si no hay datos en el contexto, usá tu conocimiento general y aclaralo. "
            "Respondé en espanol, con datos concretos y tono amigable. No uses emojis."
        )
        if contexto:
            system_prompt += "\n\nDATOS DEL DATASET PARA ESTA CONSULTA:\n" + contexto

        self.historial.append({"role": "user", "content": pregunta})
        respuesta = self._mistral(
            [{"role": "system", "content": system_prompt}] + self.historial,
            temperature=0.3,
        )
        self.historial.append({"role": "assistant", "content": respuesta})
        return respuesta

    def iniciar_sesion(self):
        """Chatbot interactivo. Escribi 'salir' para terminar."""
        print("=" * 55)
        print("Agente 3 - Comunicador (chat) | Copa del Mundo 1930-2022")
        print("=" * 55)
        if not self._tiene_key:
            print("Nota: sin API key respondo solo con datos del dataset (modo offline).")
        print("Preguntame sobre partidos, resultados o estadisticas.")
        print("Escribi 'salir' para terminar.\n")

        while True:
            pregunta = input("Vos: ").strip()
            if not pregunta:
                continue
            if pregunta.lower() in ('salir', 'exit', 'quit'):
                print("Comunicador: hasta la proxima Copa del Mundo.")
                break
            try:
                print("   Consultando...")
                print(f"\nComunicador: {self.responder(pregunta)}\n")
            except Exception as e:
                print(f"   Error: {e}")


# ----- API key de Mistral (opcional) -----
# Obtenela en https://console.mistral.ai/ y reemplaza el placeholder de abajo.
# Sin key, el reporte y el chat funcionan en modo offline (solo datos del dataset).
MISTRAL_API_KEY = "KXzIzVLpaCQfXF4qlgLetnAWSx66hj9a"

agente_comunicador = CommunicatorAgent(df=df_wc, api_key=MISTRAL_API_KEY)
reporte_final = agente_comunicador.process(metricas_modelo)

"""### Chat interactivo con el Comunicador

Ejecuta la celda de abajo y escribí tus preguntas. Para terminar, escribí `salir`.

Ejemplos:
- ¿Como le fue a Argentina en el mundial 2022?
- ¿Cual fue el resultado de la final del mundial 1986?
- ¿Que partidos jugo Brasil en 1970?
- ¿Quien gano el mundial de 1998?
"""

# Chat interactivo del Agente 3 (Comunicador).
# Necesita MISTRAL_API_KEY cargada arriba para respuestas completas;
# sin key responde en modo offline con los datos del dataset.
agente_comunicador.iniciar_sesion()

"""## Resumen del Pipeline"""

